version: '3.8'

services:
  openhim-config:
    container_name: openhim-config
    image: test-image:latest
      
  openhim-core:
    container_name: openhim-core
    hostname: openhim-core
    image: jembi/openhim-core:latest
    environment:
      mongo_url: "mongodb://mongo-db/openhim"
      mongo_atnaUrl: "mongodb://mongo-db/openhim"
      NODE_ENV: "development"
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3  
    ports:
      - 8080:8080
      - 5001:5001
      - 5000:5000
  mongo-db:
    container_name: mongo-db
    image: mongo:3.4